// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "Misc/ControllableByMIDIUI.h"
#include "Params/ControllableByMIDI.h"
#include <iostream>
// ControllableByMIDIUI.cc
// Original ZynAddSubFX author Nasca Octavian Paul
// Copyright (C) 2002-2005 Nasca Octavian Paul
// Copyright 2009-2010, Alan Calvert

// This file is part of yoshimi, which is free software: you can redistribute
// it and/or modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.

// yoshimi is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.   See the GNU General Public License (version 2 or
// later) for more details.

// You should have received a copy of the GNU General Public License along with
// yoshimi; if not, write to the Free Software Foundation, Inc., 51 Franklin
// Street, Fifth Floor, Boston, MA  02110-1301, USA.

// This file is a derivative of the ZynAddSubFX original, modified January 2010

void ControllableByMIDIUI::reassignMidi(ControllableByMIDI *ctrl)
{
	setController(ctrl);
	if(controller)
		controller->reassignUIControls(this);
}

void ControllableByMIDIUI::unassignUIControls()
{
  if(controller != NULL){
  	std::cout << "unassignUIControls " << controller << endl;
    controller->unassignUIControls();
  }
}

void ControllableByMIDIUI::setController(ControllableByMIDI *_controller)
{
	if(controller != NULL){
		std::cout << "***********Changing controller**********" << endl;
	}
	else {
		std::cout << ">>>>>>>>>>>>>>Adding Controller " << _controller << " to UI<<<<<<<<<<<<<<<<<" << endl;
	}
	controller = _controller;
}

ControllableByMIDIUI::ControllableByMIDIUI(): controller(NULL)
{

}